USE [master]
GO

/****** Object:  Database [DailyLoan]    Script Date: 03/11/2021 3:25:40 PM ******/
CREATE DATABASE [DailyLoan] ON  PRIMARY 
( NAME = N'DailyLoan', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DailyLoan.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DailyLoan_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DailyLoan_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DailyLoan].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DailyLoan] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DailyLoan] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DailyLoan] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DailyLoan] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DailyLoan] SET ARITHABORT OFF 
GO

ALTER DATABASE [DailyLoan] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DailyLoan] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DailyLoan] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DailyLoan] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DailyLoan] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DailyLoan] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DailyLoan] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DailyLoan] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DailyLoan] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DailyLoan] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DailyLoan] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DailyLoan] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DailyLoan] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DailyLoan] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DailyLoan] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DailyLoan] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DailyLoan] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DailyLoan] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DailyLoan] SET  MULTI_USER 
GO

ALTER DATABASE [DailyLoan] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DailyLoan] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DailyLoan] SET  READ_WRITE 
GO


