BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.[Contract]
	ADD ExContractPay float(53) NULL;
ALTER TABLE dbo.[Contract]
	ADD [Type] int NULL;
GO
ALTER TABLE dbo.[Contract] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
select Has_Perms_By_Name(N'dbo.Contract', 'Object', 'ALTER') as ALT_Per, Has_Perms_By_Name(N'dbo.Contract', 'Object', 'VIEW DEFINITION') as View_def_Per, Has_Perms_By_Name(N'dbo.Contract', 'Object', 'CONTROL') as Contr_Per 